### PR TITLE
Fix RPM dependencies

### PR DESCRIPTION
**Pull request by TheAssassin**

### CODE REVIEW

**Comment by TheAssassin** [comment]
@fusion809 can you please check whether the latest binaries work as intended?

https://artifacts.assassinate-you.net/artifactory/list/appimaged/travis-60/appimaged-1_alpha-gitdf39a56~travis60.x86_64.rpm

**Comment by fusion809** [comment]
I built it locally with this patch applied, tried to install the RPM and I got the exact same error again.

**Comment by TheAssassin** [comment]
@fusion809 you mean the GLib dependency error?

**Comment by fusion809** [comment]
Yep.

**Comment by fusion809** [comment]
Lol I tried to install it on Fedora Rawhide and I received a dependency error too:

```bash
$ sudo dnf install -y https://github.com/AppImage/appimaged/releases/download/continuous/appimaged-appimaged-1_alpha-gita3b100b.travis57.x86_64.rpm
Last metadata expiration check: 19:36:51 ago on Wed 21 Nov 2018 14:57:15 AEST.
appimaged-appimaged-1_alpha-gita3b100b.travis57.x86_64.rpm                           29 kB/s | 155 kB     00:05    
Error: 
 Problem: conflicting requests
  - nothing provides libarchive13 needed by appimaged-appimaged-1_alpha-gita3b100b~travis57.x86_64
  - nothing provides libglib2.0-0 needed by appimaged-appimaged-1_alpha-gita3b100b~travis57.x86_64
  - nothing provides zlib1g needed by appimaged-appimaged-1_alpha-gita3b100b~travis57.x86_64
  - nothing provides libc6 >= 2.4 needed by appimaged-appimaged-1_alpha-gita3b100b~travis57.x86_64
```

**Comment by TheAssassin** [comment]
@fusion809 you should try the one provided in Artifactory. That's where Travis build artifacts are stored (except for release/continuous builds).

**Comment by fusion809** [comment]
I gave it a go earlier as well, same error, however.

**Comment by TheAssassin** [comment]
@fusion809 if you could provide the right package names for the packages listed in that error message, I can try to overwrite them explicitly in the CPack config.

**Comment by fusion809** [comment]
Funny, RPM itself is meant to detect libraries required by files provided by the package. It does when I package RPM packages using the openSUSE Build Service. For Fedora:

- libarchive equates to libarchive13 (provides same library libarchive.so.13).
- glib2 equates to libglib2.0-0.
- zlib equates to zlib1g, both provide libz.so.1.
- glibc equates to libc6, which is provided by libc.so.6.

openSUSE:

- libglib2.0-0 provides libraries in the packages: libgio-2_0-0, libglib-2_0-0, libgmodule-2_0-0, libgobject-2_0-0 and libgthread-2_0-0.

**Comment by TheAssassin** [comment]
@fusion809 well, that may work if you build distro specific packages on the target distros. We build the RPM packages on Debian, though. Do you think the `AUTOREQ` stuff works in that scenario, too? I'm not sure about it.

What's funny is that AppImageLauncher's RPM packages install fine on openSUSE _and_ Fedora (at least when I wrote the config a few months ago...).

**Comment by fusion809** [comment]
Not sure about `AUTOREQ`, I use spec files for building my RPMs, not CMake.

**Comment by probonopd** [comment]
@TheAssassin did you see that the RPM we are currently generating has a real strange name with the application name 2x in the filename?

**Comment by TheAssassin** [comment]
That's something fixed in this PR, too (that `MAIN_COMPONENT` line).

**Comment by probonopd** [comment]
Is something missing for this to be ready for merging?

**Comment by TheAssassin** [comment]
Yes: everything. The dependency issues weren't resolved, and I didn't have any time (and neither wasn't interested enough) to look into this.

You're free to investigate this yourself.

**Comment by probonopd** [comment]
Don't have the time, sorry

**Comment by probonopd** [comment]
Does any RPM expert volunteer to take this over?

**Comment by azubieta** [comment]
fixed on  #91

**Pull request closed without merging**
