### PR TITLE
Use png rather than svg

### PR DESCRIPTION
**Pull request by probonopd**
@TheAssassin please review my CMake change. Thanks

### CODE REVIEW

**Comment by TheAssassin** [comment]
Changes make sense. Please check why the build failed. Have you forgotten to add the PNG file? We can add a command to the CMake script to generate the PNG from the SVG during the build.

**Comment by probonopd** [comment]
Thanks for reviewing. Man does CMake add chore work:

```
/applications/appimaged.desktop
CMake Error at /tmp/appimaged-build-9HIdWN/resources/cmake_install.cmake:49 (file):
  file INSTALL cannot find
  "/home/travis/build/AppImage/appimaged/resources/appimaged.png".
```

**Comment by TheAssassin** [comment]
It can't deploy a PNG you haven't added. Hardly CMake's fault?

**Comment by TheAssassin** [comment]
I can provide you with a command that generates the PNG from the SVG that you can add above the `install(...)` directive.

**Comment by probonopd** [comment]
Where is the dreaded INSTALL file?

**Comment by TheAssassin** [comment]
```
execute_process(
    COMMAND rsvg-convert -w 128 ${CMAKE_CURRENT_SOURCE_DIR}/appimage.svg > ${CMAKE_CURRENT_BINARY_DIR}/appimage.png
)
```

Then, change the path to `CMAKE_CURRENT_BINARY_DIR` in your install command (auto generated files never should end up in the source tree, we put it into the build directory therefore).

This change requires `rsvg-convert` to be installed. The package for Ubuntu/Debian is `librsvg2-bin`. It's the highest quality SVG converter I know.

**Comment by TheAssassin** [comment]
> Where is the dreaded INSTALL file?

What do you mean?

**Comment by probonopd** [comment]
OK, I see, the filename is `appimage.png` but needs to be `appimaged.png`. Now, I have no clue how to append this rename to an already-open PR...

**Comment by probonopd** [comment]
> What do you mean?

The error message suggests there there is an INSTALL file which is missing the name of the icon:

>   file INSTALL cannot find
>  "/home/travis/build/AppImage/appimaged/resources/appimaged.png".

Misleading wording. Would have cost me a _lot_ of time searching the problem in the entirely wrong places.

**Comment by TheAssassin** [comment]
Well, to me, it's pretty clear, there's different `install(...)` commands, one is `install(FILE ...)`, which it refers to. But you might want to suggest a better wording upstream.

Anyway, does it work now?

**Comment by probonopd** [comment]
No, I have no clue how to append this rename to an already-open PR...

**Comment by TheAssassin** [comment]
What's "appending a rename"?

**Comment by probonopd** [comment]
We need to rename the png file. How can I do this rename so that it shows up in this PR?

**Comment by probonopd** [comment]
> you might want to suggest a better wording upstream.

https://gitlab.kitware.com/cmake/cmake/issues/19950

**Comment by TheAssassin** [comment]
Err... clone, rename, commit, push? There's likely a way on GitHub too. Just change it in the branch used for this PR. It's called `use-png`?

**Comment by probonopd** [comment]
Ah right...

**Comment by probonopd** [comment]
Ready to merge?

**Comment by TheAssassin** [comment]
Haven't checked the logs, but everything seems fine. Yup, ready to merge.

**Pull request merged**
