### PR TITLE
Follow symlinks

### PR DESCRIPTION
**Pull request by cadadr**
This patch enables appimaged to follow symlinks, in case any of the paths under which it looks for appimages happens to be a symlink. I have tried to keep the silent failure behaviour as much as possible, but a new potential error message is added in case following the symlink fails for some reason.

I don't think this aspect needs to be configurable, but if you want it to be, I might try add a command line option toggling this behaviour. Should be simple.

### CODE REVIEW

**Comment by probonopd** [comment]
Thank you very much @cadadr. Please be aware that likely we will move to the new codebase written in Go at some point which currently is experimental. If you would like to have a look, it is currently at https://github.com/probonopd/go-appimage/tree/master/src/appimaged.

**Comment by cadadr** [comment]
You’re welcome! I’m not very familiar with Go but I’ll have a look. At a
first glance, I’m curious why you didn’t use
https://github.com/fsnotify/fsnotify tho. I used it a few years ago for
a little CLI tool and it was pleasant to work with.

**Comment by probonopd** [comment]
Thanks, will check it out.

**Comment by cadadr** [comment]
BTW I noticed a bug that I've slipped in this patch at https://github.com/AppImage/appimaged/blob/master/src/main.c#L369, I've forgotten to negate the RHS of the OR expression. Should I send a PR or would you rather just add the `!` after the `||`?

**Comment by probonopd** [comment]
Thanks for noticing @cadadr, would appreciate another PR.

**Pull request merged**
