### PR TITLE
Remove workaround for hidden dependencies

### PR DESCRIPTION
**Pull request by probonopd**
https://github.com/AppImage/libappimage/pull/118

### CODE REVIEW

**Comment by probonopd** [comment]
```
The following packages have unmet dependencies:
 librsvg2-dev:i386 : Depends: gir1.2-rsvg-2.0:i386 (= 2.40.2-1) but it is not going to be installed
                     Depends: libgdk-pixbuf2.0-dev:i386 (>= 2.23.5-2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by probonopd** [comment]
@TheAssassin any clue what to do?

**Comment by azubieta** [comment]
Sorry, had a busy day. Been trying to reproduce the issue and seems like the Travis guys break it again.

While trying to run `apt-get update && apt-get install` manually (not using the plugin thing) I get the [some errors](https://travis-ci.org/AppImage/appimaged/jobs/536596526#L1700) related to the repositories configuration.

**Comment by azubieta** [comment]
Finally, a green build!

**Pull request merged**
